#!/usr/bin/env python3
"""Generate the precision-landing world, its ArUco marker textures and rover models.

Produces (all paths relative to the repo root):

  models/aruco_rover_<N>/materials/textures/aruco_<N>.png
  models/aruco_rover_<N>/model.config
  models/aruco_rover_<N>/model.sdf
  worlds/fei_lrs_precision_landing.world

The drone body is not written by hand: it is lifted out of
worlds/fei_lrs_outdoor.world and re-emitted once per drone with a distinct
model name, link prefix, ArduPilot FDM port and spawn pose, and with the
stereo camera pair swapped for a single down-facing camera.

Rerun this script after changing the outdoor world's drone, or after changing
any of the constants below.
"""

import re
import sys
from pathlib import Path

import cv2
import numpy as np

REPO = Path(__file__).resolve().parent.parent
SRC_WORLD = REPO / "worlds" / "fei_lrs_outdoor.world"
OUT_WORLD = REPO / "worlds" / "fei_lrs_precision_landing.world"

# ArUco marker id N is paired with the drone whose MAVLink SYSID_THISMAV is N.
ARUCO_DICT = cv2.aruco.DICT_4X4_50
MARKER_PX = 800          # texture resolution of the marker itself
QUIET_ZONE_CELLS = 1     # white border, in marker cells (ArUco needs one)

PAD_SIZE = 1.00          # landing pad plate, metres square
MARKER_SIZE = 0.85       # printed marker on that plate, metres square
CIRCLE_RADIUS = 3.0      # metres
CIRCLE_SPEED = 0.30      # m/s  -> angular = speed / radius

# A 0.85 m marker in a 640 px / 60 deg camera subtends ~48 px at 10 m and
# ~24 px at 20 m; ArUco needs roughly 20 px, so detection holds to about 20 m.

# Per-vehicle setup. Marker id == SITL instance + 1 == SYSID_THISMAV.
VEHICLES = [
    {
        "marker_id": 1,
        "sysid": 1,
        "instance": 0,
        "fdm_port": 9002,
        "drone_pose": (-10.0, -10.0, 0.005, 0.0),   # x, y, z, yaw
        "circle_center": (-10.0, 2.0),
    },
    {
        "marker_id": 2,
        "sysid": 2,
        "instance": 1,
        "fdm_port": 9012,
        "drone_pose": (10.0, -10.0, 0.005, 0.0),
        "circle_center": (10.0, 2.0),
    },
]


def generate_marker_png(marker_id: int, path: Path) -> None:
    """Write an ArUco marker PNG with the white quiet zone detection requires."""
    # cv2.aruco was renamed in OpenCV 4.7; support both spellings.
    if hasattr(cv2.aruco, "getPredefinedDictionary"):
        dictionary = cv2.aruco.getPredefinedDictionary(ARUCO_DICT)
    else:
        dictionary = cv2.aruco.Dictionary_get(ARUCO_DICT)

    if hasattr(cv2.aruco, "generateImageMarker"):
        img = cv2.aruco.generateImageMarker(dictionary, marker_id, MARKER_PX)
    else:
        img = cv2.aruco.drawMarker(dictionary, marker_id, MARKER_PX)

    # The generator emits the black border but no quiet zone; add one.
    marker_bits = getattr(dictionary, "markerSize", None)
    if marker_bits is None:                    # OpenCV 4.6 exposes it here
        marker_bits = dictionary.markerSize
    cells = marker_bits + 2                    # marker bits + black border
    px_per_cell = MARKER_PX // cells
    pad = px_per_cell * QUIET_ZONE_CELLS
    img = cv2.copyMakeBorder(
        img, pad, pad, pad, pad, cv2.BORDER_CONSTANT, value=255
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(path), img)


def rover_model_sdf(v: dict) -> str:
    """A four-wheeled platform carrying an ArUco landing pad, driving a circle.

    Motion comes from VelocityControl rather than from the wheels: it applies a
    body-frame twist, so a constant (v, w) traces an exact circle of radius
    v/w around a centre r to the vehicle's left. The wheels are cosmetic.
    """
    mid = v["marker_id"]
    angular = CIRCLE_SPEED / CIRCLE_RADIUS
    half = PAD_SIZE / 2.0

    wheels = []
    for i, (wx, wy) in enumerate(
        [(0.3, 0.33), (0.3, -0.33), (-0.3, 0.33), (-0.3, -0.33)]
    ):
        wheels.append(f"""        <visual name='wheel_{i}'>
          <pose>{wx} {wy} 0.12 1.5708 0 0</pose>
          <geometry>
            <cylinder><radius>0.12</radius><length>0.09</length></cylinder>
          </geometry>
          <material>
            <ambient>0.02 0.02 0.02 1</ambient>
            <diffuse>0.10 0.10 0.10 1</diffuse>
            <specular>0.02 0.02 0.02 1</specular>
          </material>
        </visual>""")

    return f"""<?xml version="1.0"?>
<sdf version="1.9">
  <!-- Generated by scripts/generate_precision_landing.py - do not edit by hand. -->
  <model name="aruco_rover_{mid}">
    <link name="base_link">
      <inertial>
        <mass>20</mass>
        <inertia>
          <ixx>1.2</ixx><ixy>0</ixy><ixz>0</ixz>
          <iyy>1.6</iyy><iyz>0</iyz><izz>2.0</izz>
        </inertia>
        <pose>0 0 0.2 0 0 0</pose>
      </inertial>

      <visual name='chassis'>
        <pose>0 0 0.22 0 0 0</pose>
        <geometry>
          <box><size>1.00 0.80 0.16</size></box>
        </geometry>
        <material>
          <ambient>0.15 0.15 0.17 1</ambient>
          <diffuse>0.35 0.36 0.40 1</diffuse>
          <specular>0.10 0.10 0.10 1</specular>
        </material>
      </visual>
{chr(10).join(wheels)}

      <!-- White plate the marker is printed on; gives the marker its quiet
           zone in 3D as well as in the texture. -->
      <visual name='pad'>
        <pose>0 0 0.305 0 0 0</pose>
        <geometry>
          <box><size>{PAD_SIZE} {PAD_SIZE} 0.02</size></box>
        </geometry>
        <material>
          <ambient>0.85 0.85 0.85 1</ambient>
          <diffuse>0.95 0.95 0.95 1</diffuse>
          <specular>0.05 0.05 0.05 1</specular>
        </material>
      </visual>

      <!-- The marker itself, a hair above the plate so it never z-fights. -->
      <visual name='aruco_marker'>
        <pose>0 0 0.3165 0 0 0</pose>
        <geometry>
          <box><size>{MARKER_SIZE} {MARKER_SIZE} 0.001</size></box>
        </geometry>
        <material>
          <ambient>1 1 1 1</ambient>
          <diffuse>1 1 1 1</diffuse>
          <specular>0 0 0 1</specular>
          <pbr>
            <metal>
              <albedo_map>model://aruco_rover_{mid}/materials/textures/aruco_{mid}.png</albedo_map>
              <metalness>0</metalness>
              <roughness>1</roughness>
            </metal>
          </pbr>
        </material>
      </visual>

      <!-- Single box collision covering chassis + pad, so a drone can rest on
           the pad surface at z = 0.315. -->
      <collision name='collision'>
        <pose>0 0 0.19 0 0 0</pose>
        <geometry>
          <box><size>1.00 0.80 0.25</size></box>
        </geometry>
        <surface>
          <friction>
            <ode><mu>100</mu><mu2>50</mu2></ode>
          </friction>
        </surface>
      </collision>
    </link>

    <plugin filename="gz-sim-velocity-control-system"
            name="gz::sim::systems::VelocityControl">
      <initial_linear>{CIRCLE_SPEED} 0 0</initial_linear>
      <initial_angular>0 0 {angular:.6f}</initial_angular>
    </plugin>

    <plugin filename="gz-sim-odometry-publisher-system"
            name="gz::sim::systems::OdometryPublisher">
      <odom_frame>world</odom_frame>
      <robot_base_frame>aruco_rover_{mid}</robot_base_frame>
      <odom_publish_frequency>20</odom_publish_frequency>
      <odom_topic>model/aruco_rover_{mid}/odometry</odom_topic>
    </plugin>
  </model>
</sdf>
"""


def rover_model_config(v: dict) -> str:
    mid = v["marker_id"]
    return f"""<?xml version="1.0"?>
<model>
  <name>aruco_rover_{mid}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>
    Rover carrying ArUco marker id {mid} (DICT_4X4_50) on a {PAD_SIZE}m landing
    pad, driving a {CIRCLE_RADIUS}m-radius circle. Landing target for the drone
    with SYSID_THISMAV {v["sysid"]}.
  </description>
</model>
"""


def down_camera_xml(prefix: str) -> str:
    """A single nadir camera, replacing the outdoor world's stereo pair."""
    return f"""        <sensor name='down_camera' type='camera'>
          <pose>0 0 0 0 1.5708 0</pose>
          <topic>{prefix}/down_camera/image_raw</topic>
          <update_rate>30</update_rate>
          <camera name='down'>
            <horizontal_fov>1.047</horizontal_fov>
            <image>
              <width>640</width>
              <height>480</height>
              <format>R8G8B8</format>
            </image>
            <clip>
              <near>0.05</near>
              <far>300</far>
            </clip>
            <noise>
              <type>gaussian</type>
              <mean>0</mean>
              <stddev>0.005</stddev>
            </noise>
          </camera>
          <always_on>1</always_on>
          <visualize>true</visualize>
        </sensor>
"""


def extract_drone_block(world_text: str) -> str:
    start = world_text.index("    <model name='fei_lrs_drone'>")
    end = world_text.index("    </model>", start) + len("    </model>\n")
    return world_text[start:end]


def build_drone(template: str, v: dict) -> str:
    """Re-emit the template drone as drone_<sysid> with a nadir camera."""
    sysid = v["sysid"]
    name = f"drone_{sysid}"
    block = template

    # Model name and every link/joint/sensor path that embeds the old name.
    block = block.replace(
        "<model name='fei_lrs_drone'>", f"<model name='{name}'>"
    )
    block = block.replace("fei_lrs_drone/", f"{name}/")

    # ...but the mesh URIs are paths into the shared fei_lrs_drone model
    # directory, not link names, so put those back.
    block = block.replace(f"model://{name}/", "model://fei_lrs_drone/")

    # Swap the stereo pair for one down-facing camera. The sensors sit between
    # the link's <inertial> block and its trailing <self_collide>. Sensor names
    # are unprefixed in the template, unlike link names.
    cam_start = block.index("<sensor name='stereo_camera_left'")
    cam_end = block.index("        <self_collide>", cam_start)
    block = block[:cam_start] + down_camera_xml(name).lstrip() + block[cam_end:]

    # Point the camera link at the belly instead of the stereo mount, and
    # rename it to match its new role.
    block = block.replace(
        f"<link name='{name}/stereo_cam_link'>",
        f"<link name='{name}/down_cam_link'>",
    )
    block = block.replace(
        f"<child>{name}/stereo_cam_link</child>",
        f"<child>{name}/down_cam_link</child>",
    )
    block = block.replace(
        "<pose>0.085000000000000006 0.050000000000000003 "
        "0.073499999999999996 0 0 0</pose>",
        "<pose>0 0 -0.03 0 0 0</pose>",
    )

    # Distinct FDM port so each SITL instance binds its own drone.
    block = block.replace(
        "<fdm_port_in>9002</fdm_port_in>",
        f"<fdm_port_in>{v['fdm_port']}</fdm_port_in>",
    )

    # Spawn pose.
    x, y, z, yaw = v["drone_pose"]
    block = block.replace(
        "      <pose>0 0 0.005 0 0 0</pose>\n    </model>",
        f"      <pose>{x} {y} {z} 0 0 {yaw}</pose>\n    </model>",
    )
    return block


def build_gui_camera_panels() -> str:
    panels = []
    for i, v in enumerate(VEHICLES):
        name = f"drone_{v['sysid']}"
        panels.append(f"""      <plugin filename="ImageDisplay" name="Drone {v['sysid']} down camera">
        <gz-gui>
          <title>Drone {v['sysid']} down camera</title>
          <property key="state" type="string">floating</property>
          <property type="double" key="width">350</property>
          <property type="double" key="height">315</property>
          <property type="double" key="x">{i * 360}</property>
        </gz-gui>
        <topic>{name}/down_camera/image_raw</topic>
        <topic_picker>false</topic_picker>
      </plugin>""")
    return "\n".join(panels)


def check_clearance(src: str) -> None:
    """Fail loudly if a landing circle or spawn point overlaps inherited scenery.

    The outdoor world's trees are static obstacles; a rover driving into one
    would stall against it and the exercise would silently break.
    """
    trees = re.findall(
        r"<model name='((?:tree|bush)\w*)'>\s*<static>true</static>\s*"
        r"<pose>(-?[\d.]+) (-?[\d.]+) ",
        src,
    )
    if not trees:
        raise SystemExit("no trees found in source world - has its format changed?")

    problems = []
    for v in VEHICLES:
        cx, cy = v["circle_center"]
        dx, dy = v["drone_pose"][0], v["drone_pose"][1]
        for name, tx, ty in trees:
            tx, ty = float(tx), float(ty)
            # Trees have canopies up to ~3.5 m radius; keep the driven circle
            # and the spawn pad well outside that.
            ring_gap = abs(((tx - cx) ** 2 + (ty - cy) ** 2) ** 0.5 - CIRCLE_RADIUS)
            if ring_gap < 5.0:
                problems.append(
                    f"  {name} at ({tx}, {ty}) is {ring_gap:.1f} m from "
                    f"drone_{v['sysid']}'s circle"
                )
            spawn_gap = ((tx - dx) ** 2 + (ty - dy) ** 2) ** 0.5
            if spawn_gap < 5.0:
                problems.append(
                    f"  {name} at ({tx}, {ty}) is {spawn_gap:.1f} m from "
                    f"drone_{v['sysid']}'s spawn"
                )
    if problems:
        raise SystemExit("scenery conflicts:\n" + "\n".join(problems))
    print(f"clearance OK against {len(trees)} trees/bushes")


def main() -> int:
    if not SRC_WORLD.exists():
        raise SystemExit(f"source world not found: {SRC_WORLD}")
    src = SRC_WORLD.read_text()
    check_clearance(src)

    # --- marker textures + rover models -------------------------------------
    for v in VEHICLES:
        mid = v["marker_id"]
        model_dir = REPO / "models" / f"aruco_rover_{mid}"
        generate_marker_png(
            mid, model_dir / "materials" / "textures" / f"aruco_{mid}.png"
        )
        (model_dir / "model.sdf").write_text(rover_model_sdf(v))
        (model_dir / "model.config").write_text(rover_model_config(v))
        print(f"wrote models/aruco_rover_{mid}/")

    # --- world ---------------------------------------------------------------
    drone_template = extract_drone_block(src)

    # Everything above the drone is reused as-is: lights, ground plane, trees.
    head = src[: src.index("    <model name='fei_lrs_drone'>")]
    tail = src[src.index("    <gravity>0 0 -9.8") :]

    head = head.replace(
        "<world name='fei_lrs_outdoor_world'>",
        "<world name='fei_lrs_precision_landing_world'>",
    )

    # Replace the stereo GUI panels with one per drone's nadir camera.
    gui_start = head.index('      <plugin filename="ImageDisplay" name="Left camera">')
    gui_end = head.index("    </gui>", gui_start)
    head = head[:gui_start] + build_gui_camera_panels() + "\n" + head[gui_end:]

    # Pull the camera back for a view that takes in both landing circles.
    head = head.replace(
        "<camera_pose>-50 -65 40 0 0.45 0.9</camera_pose>",
        "<camera_pose>0 -34 26 0 0.62 1.5708</camera_pose>",
    )

    header = f"""<sdf version='1.9'>
<!--
  GENERATED by scripts/generate_precision_landing.py - do not edit by hand.

  Precision-landing exercise, built on the fei_lrs_outdoor field
  (48.15144444, 17.07375000 at the world origin).

  Two drones, each with a nadir camera, and two rovers each carrying an ArUco
  marker (DICT_4X4_50) on a {PAD_SIZE}m landing pad. Marker id == the drone's
  SYSID_THISMAV: drone_1 finds and follows marker 1, drone_2 marker 2 -- this
  is a find-and-follow exercise, not precision landing; see
  assignments/assignment2/rover-find-and-follow.md.

  Each rover starts on a {CIRCLE_RADIUS}m-radius circle at {CIRCLE_SPEED} m/s
  ({CIRCLE_SPEED / CIRCLE_RADIUS:.3f} rad/s), needing no external command to
  move from t = 0. A randomizer node (yours to write -- see the assignment)
  then takes over with a randomly changing speed/yaw-rate Twist on
  model/aruco_rover_<N>/cmd_vel, so the motion is no longer just that solved
  circle once it is running.

  ArduPilot SITL: drone_1 is instance 0 (FDM port 9002, sysid 1), drone_2 is
  instance 1 (FDM port 9012, sysid 2). See
  assignments/assignment2/rover-find-and-follow.md for what to bring up and
  in what order.
-->
"""
    body = head[head.index("  <world name="):]
    drones = "".join(build_drone(drone_template, v) for v in VEHICLES)

    rovers = []
    for v in VEHICLES:
        mid = v["marker_id"]
        cx, cy = v["circle_center"]
        # VelocityControl circles to the vehicle's left, so start it r to the
        # centre's +x with a +90 deg yaw to put the centre at (cx, cy).
        rovers.append(f"""    <include>
      <uri>model://aruco_rover_{mid}</uri>
      <name>aruco_rover_{mid}</name>
      <pose>{cx + CIRCLE_RADIUS} {cy} 0 0 0 1.5708</pose>
    </include>
""")

    OUT_WORLD.write_text(header + body + drones + "".join(rovers) + tail)
    print(f"wrote {OUT_WORLD.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
