#!/usr/bin/env bash
<<<<<<< Updated upstream
# Install the Ubuntu 24.04 prerequisites for LRS-URK.
#
# Optional path overrides:
#   ARDUPILOT_DIR="$HOME/ardupilot" \
#   ARDUPILOT_GAZEBO_DIR="$HOME/ardupilot_gazebo" \
#     scripts/install_ubuntu_24.sh
set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
readonly STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/lrs-urk-installer"
readonly STATE_FILE="$STATE_DIR/manifest.env"
readonly BASHRC_FILE="${BASHRC_FILE:-$HOME/.bashrc}"
readonly ENV_START='# >>> LRS-URK installer >>>'
readonly ENV_END='# <<< LRS-URK installer <<<'
readonly LRS_URK_REMOTE='https://github.com/KocurMaros/LRS-URK.git'

REQUESTED_ARDUPILOT_DIR="$(realpath -m -- "${ARDUPILOT_DIR:-$HOME/ardupilot}")"
REQUESTED_ARDUPILOT_GAZEBO_DIR="$(realpath -m -- "${ARDUPILOT_GAZEBO_DIR:-$HOME/ardupilot_gazebo}")"
REQUESTED_GAZEBO_BUILD_DIR="$(realpath -m -- "${ARDUPILOT_GAZEBO_BUILD_DIR:-$REQUESTED_ARDUPILOT_GAZEBO_DIR/build}")"
ROS_DISTRO="${ROS_DISTRO:-jazzy}"
GZ_VERSION="${GZ_VERSION:-harmonic}"
ARDUPILOT_REF="${ARDUPILOT_REF:-Copter-4.7.0}"
ARDUPILOT_GAZEBO_REF="${ARDUPILOT_GAZEBO_REF:-ros2}"
WITH_SYSTEM_UPGRADE=0
CHECK_ONLY=0
TMP_ROS_DEB=''
TMP_APT_SNAPSHOT=''

CREATED_ARDUPILOT=0
CREATED_ARDUPILOT_GAZEBO=0
CREATED_GAZEBO_BUILD=0
CREATED_GAZEBO_ROSDEP_SOURCE=0
CREATED_DEFAULT_ROSDEP_SOURCE=0
INSTALLED_ROS_APT_SOURCE=0
NEW_PACKAGES=()
REMOVED_PACKAGES=()
ADDED_DIALOUT=0
ARDUPILOT_VENV_DIR=''

log() { printf '\n[LRS-URK] %s\n' "$*"; }
die() { printf '\n[LRS-URK] ERROR: %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<'EOF'
Usage: scripts/install_ubuntu_24.sh [options]

Install ROS 2 Jazzy, Gazebo Harmonic integration, MAVROS, ArduPilot, the
ArduPilot Gazebo plugin, Git LFS assets, and the required shell environment.

Options:
  --check                Only validate Ubuntu, Git, and GitHub access.
  --with-system-upgrade  Run a full apt-get upgrade before installing packages.
  -h, --help             Show this help.

Default source locations:
  ~/ardupilot
  ~/ardupilot_gazebo

Override them with ARDUPILOT_DIR and ARDUPILOT_GAZEBO_DIR. Other supported
overrides are ARDUPILOT_GAZEBO_BUILD_DIR, ARDUPILOT_REF,
ARDUPILOT_GAZEBO_REF, ROS_DISTRO, GZ_VERSION, and BASHRC_FILE.
EOF
}

while (($#)); do
  case "$1" in
    --check) CHECK_ONLY=1 ;;
    --with-system-upgrade) WITH_SYSTEM_UPGRADE=1 ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown option: $1 (use --help)" ;;
  esac
  shift
done

cleanup() {
  [[ -z "$TMP_ROS_DEB" || ! -f "$TMP_ROS_DEB" ]] || rm -f -- "$TMP_ROS_DEB"
  [[ -z "$TMP_APT_SNAPSHOT" || ! -f "$TMP_APT_SNAPSHOT" ]] || rm -f -- "$TMP_APT_SNAPSHOT"
}
trap cleanup EXIT
trap 'die "Command failed on line $LINENO: $BASH_COMMAND"' ERR

[[ $EUID -ne 0 ]] || die "Run this script as your normal user, not as root. It uses sudo when needed."
[[ "$ROS_DISTRO" =~ ^[a-z0-9_]+$ ]] || die "Invalid ROS_DISTRO: $ROS_DISTRO"
[[ "$GZ_VERSION" =~ ^[a-z0-9_]+$ ]] || die "Invalid GZ_VERSION: $GZ_VERSION"
=======
set -euo pipefail

ARDUPILOT_DIR="${ARDUPILOT_DIR:-$HOME/ardupilot}"
ARDUPILOT_GAZEBO_DIR="${ARDUPILOT_GAZEBO_DIR:-$HOME/ardupilot_gazebo}"
ROS_DISTRO=jazzy
GZ_VERSION=harmonic
LRS_URK_REMOTE=https://github.com/KocurMaros/LRS-URK.git
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LRS_URK_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BASHRC="$HOME/.bashrc"
ENV_START='# >>> LRS-URK >>>'
ENV_END='# <<< LRS-URK <<<'
CHECK_ONLY=0
case "${1:-}" in
  --check) CHECK_ONLY=1 ;;
  -h|--help)
    echo "Usage: scripts/install_ubuntu_24.sh [--check]"
    exit 0
    ;;
  '') ;;
  *) echo "Unknown option: $1" >&2; exit 1 ;;
esac


log() { printf '\n==> %s\n' "$*"; }
fail() { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

[[ $EUID -ne 0 ]] || fail "Run this script as your normal user, not as root."
>>>>>>> Stashed changes

# shellcheck disable=SC1091
source /etc/os-release
[[ "${ID:-}" == ubuntu && "${VERSION_ID:-}" == 24.04 ]] || \
<<<<<<< Updated upstream
  die "Ubuntu 24.04 is required; detected ${PRETTY_NAME:-an unknown operating system}."

if [[ -f "$STATE_FILE" ]]; then
  # Generated by save_state below and writable only by the current user.
  # shellcheck disable=SC1090
  source "$STATE_FILE"
  [[ "${STATE_VERSION:-}" == 1 ]] || die "Unsupported installer state in $STATE_FILE"
  [[ "$ARDUPILOT_DIR" == "$REQUESTED_ARDUPILOT_DIR" ]] || \
    die "The previous install used ARDUPILOT_DIR=$ARDUPILOT_DIR. Uninstall it before choosing a new path."
  [[ "$ARDUPILOT_GAZEBO_DIR" == "$REQUESTED_ARDUPILOT_GAZEBO_DIR" ]] || \
    die "The previous install used ARDUPILOT_GAZEBO_DIR=$ARDUPILOT_GAZEBO_DIR. Uninstall it before choosing a new path."
  [[ "$ARDUPILOT_GAZEBO_BUILD_DIR" == "$REQUESTED_GAZEBO_BUILD_DIR" ]] || \
    die "The previous install used ARDUPILOT_GAZEBO_BUILD_DIR=$ARDUPILOT_GAZEBO_BUILD_DIR."
else
  ARDUPILOT_DIR="$REQUESTED_ARDUPILOT_DIR"
  ARDUPILOT_GAZEBO_DIR="$REQUESTED_ARDUPILOT_GAZEBO_DIR"
  ARDUPILOT_GAZEBO_BUILD_DIR="$REQUESTED_GAZEBO_BUILD_DIR"
  LRS_URK_DIR="$PROJECT_ROOT"
fi

[[ "$LRS_URK_DIR" == "$PROJECT_ROOT" ]] || \
  die "The saved install belongs to $LRS_URK_DIR, but this script is in $PROJECT_ROOT."
[[ "$ARDUPILOT_DIR" == "$HOME/"* ]] || \
  die "ARDUPILOT_DIR must be inside your home directory: $ARDUPILOT_DIR"
[[ "$ARDUPILOT_GAZEBO_DIR" == "$HOME/"* ]] || \
  die "ARDUPILOT_GAZEBO_DIR must be inside your home directory: $ARDUPILOT_GAZEBO_DIR"
[[ "$ARDUPILOT_GAZEBO_BUILD_DIR" == "$ARDUPILOT_GAZEBO_DIR/"* ]] || \
  die "ARDUPILOT_GAZEBO_BUILD_DIR must be inside $ARDUPILOT_GAZEBO_DIR"

save_state() {
  local state_tmp
  mkdir -p "$STATE_DIR"
  state_tmp="$(mktemp "$STATE_DIR/.manifest.XXXXXX")"
  chmod 600 "$state_tmp"
  {
    printf 'STATE_VERSION=1\n'
    printf 'ARDUPILOT_DIR=%q\n' "$ARDUPILOT_DIR"
    printf 'ARDUPILOT_GAZEBO_DIR=%q\n' "$ARDUPILOT_GAZEBO_DIR"
    printf 'ARDUPILOT_GAZEBO_BUILD_DIR=%q\n' "$ARDUPILOT_GAZEBO_BUILD_DIR"
    printf 'LRS_URK_DIR=%q\n' "$LRS_URK_DIR"
    printf 'CREATED_ARDUPILOT=%q\n' "$CREATED_ARDUPILOT"
    printf 'CREATED_ARDUPILOT_GAZEBO=%q\n' "$CREATED_ARDUPILOT_GAZEBO"
    printf 'CREATED_GAZEBO_BUILD=%q\n' "$CREATED_GAZEBO_BUILD"
    printf 'CREATED_GAZEBO_ROSDEP_SOURCE=%q\n' "$CREATED_GAZEBO_ROSDEP_SOURCE"
    printf 'CREATED_DEFAULT_ROSDEP_SOURCE=%q\n' "$CREATED_DEFAULT_ROSDEP_SOURCE"
    printf 'INSTALLED_ROS_APT_SOURCE=%q\n' "$INSTALLED_ROS_APT_SOURCE"
    printf 'ADDED_DIALOUT=%q\n' "$ADDED_DIALOUT"
    printf 'ARDUPILOT_VENV_DIR=%q\n' "$ARDUPILOT_VENV_DIR"
    printf 'NEW_PACKAGES=('
    if ((${#NEW_PACKAGES[@]})); then
      printf ' %q' "${NEW_PACKAGES[@]}"
    fi
    printf ' )\n'
    printf 'REMOVED_PACKAGES=('
    if ((${#REMOVED_PACKAGES[@]})); then
      printf ' %q' "${REMOVED_PACKAGES[@]}"
    fi
    printf ' )\n'
  } > "$state_tmp"
  mv -f -- "$state_tmp" "$STATE_FILE"
}

array_contains() {
  local wanted="$1" item
  shift
  for item in "$@"; do
    [[ "$item" == "$wanted" ]] && return 0
  done
  return 1
}

record_new_apt_packages() {
  local package
  while IFS= read -r package; do
    if [[ -n "$package" ]] && ! array_contains "$package" "${NEW_PACKAGES[@]}"; then
      NEW_PACKAGES+=("$package")
    fi
  done < <(
    comm -13 "$TMP_APT_SNAPSHOT" <(
      dpkg-query -W -f='${binary:Package} ${db:Status-Abbrev}\n' 2>/dev/null |
        awk '$2 == "ii" { print $1 }' | sort -u
    )
  )
}

package_installed() {
  dpkg-query -W -f='${db:Status-Abbrev}' "$1" 2>/dev/null | grep -q '^ii '
}

install_packages() {
  local package
  for package in "$@"; do
    if ! package_installed "$package" && ! array_contains "$package" "${NEW_PACKAGES[@]}"; then
      NEW_PACKAGES+=("$package")
    fi
  done
  save_state
  sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y "$@"
}

check_git_access() {
  command -v git >/dev/null 2>&1 || return 2

  log "Checking GitHub repository access"
  if ! GIT_TERMINAL_PROMPT=0 timeout 30 git ls-remote --exit-code \
      https://github.com/ArduPilot/ardupilot.git HEAD >/dev/null 2>&1; then
    die "Git cannot reach GitHub over HTTPS. Check your network, proxy, certificates, and Git configuration."
  fi
  if ! GIT_TERMINAL_PROMPT=0 timeout 30 git ls-remote --exit-code \
      https://github.com/ArduPilot/ardupilot_gazebo.git HEAD >/dev/null 2>&1; then
    die "Git cannot read the ArduPilot Gazebo repository. Check your GitHub/network configuration."
  fi

  git -C "$PROJECT_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1 || \
    die "$PROJECT_ROOT is not a Git checkout; clone LRS-URK with Git before running this installer."
  if ! GIT_TERMINAL_PROMPT=0 timeout 30 git ls-remote --exit-code \
      "$LRS_URK_REMOTE" HEAD >/dev/null 2>&1; then
    die "Git cannot read $LRS_URK_REMOTE. Check your GitHub/network configuration, then retry."
  fi
}

configure_project_origin() {
  local current_origin
  current_origin="$(git -C "$PROJECT_ROOT" remote get-url origin 2>/dev/null || true)"
  if [[ -z "$current_origin" ]]; then
    git -C "$PROJECT_ROOT" remote add origin "$LRS_URK_REMOTE"
  elif [[ "$current_origin" != "$LRS_URK_REMOTE" ]]; then
    log "Changing LRS-URK origin from $current_origin to $LRS_URK_REMOTE"
    git -C "$PROJECT_ROOT" remote set-url origin "$LRS_URK_REMOTE"
  fi
}

if ((CHECK_ONLY)); then
  command -v git >/dev/null 2>&1 || \
    die "Git is not installed. A normal installer run would install it automatically."
  check_git_access
  log "Preflight checks passed"
  exit 0
fi

log "Requesting sudo access"
sudo -v

if ! command -v git >/dev/null 2>&1; then
  log "Git is missing; installing it first"
  sudo apt-get update
  install_packages git ca-certificates
fi

check_git_access
configure_project_origin
save_state

log "Installing base tools and configuring the locale"
sudo apt-get update
install_packages locales software-properties-common curl ca-certificates git-lfs \
=======
  fail "This installer requires Ubuntu 24.04."

log "Checking Git"
if ! command -v git >/dev/null 2>&1; then
  sudo apt update
  sudo apt install -y git
fi

if ! GIT_TERMINAL_PROMPT=0 timeout 30 git ls-remote "$LRS_URK_REMOTE" HEAD >/dev/null 2>&1; then
  fail "Git cannot access GitHub. Check your internet connection and GitHub configuration."
fi
if (( CHECK_ONLY )); then
  echo "Ubuntu 24.04, Git, and GitHub access are OK."
  exit 0
fi


git -C "$LRS_URK_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1 || \
  fail "$LRS_URK_DIR is not a Git checkout. Clone $LRS_URK_REMOTE first."
if git -C "$LRS_URK_DIR" remote get-url origin >/dev/null 2>&1; then
  git -C "$LRS_URK_DIR" remote set-url origin "$LRS_URK_REMOTE"
else
  git -C "$LRS_URK_DIR" remote add origin "$LRS_URK_REMOTE"
fi

log "Installing Ubuntu and ROS 2 prerequisites"
sudo apt update
sudo apt install -y locales software-properties-common curl ca-certificates git-lfs \
>>>>>>> Stashed changes
  build-essential cmake pkg-config wget
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8
sudo add-apt-repository -y universe

<<<<<<< Updated upstream
log "Installing the ROS 2 apt repository"
if ! package_installed ros2-apt-source; then
=======
if ! dpkg-query -W ros2-apt-source >/dev/null 2>&1; then
>>>>>>> Stashed changes
  ROS_APT_SOURCE_VERSION="$(
    curl -fsSL https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest |
      sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' |
      head -n 1
  )"
<<<<<<< Updated upstream
  [[ -n "$ROS_APT_SOURCE_VERSION" ]] || die "Could not determine the current ros2-apt-source release."
  TMP_ROS_DEB="$(mktemp /tmp/ros2-apt-source.XXXXXX.deb)"
  curl -fL -o "$TMP_ROS_DEB" \
    "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.${UBUNTU_CODENAME:-${VERSION_CODENAME}}_all.deb"
  sudo dpkg -i "$TMP_ROS_DEB"
  INSTALLED_ROS_APT_SOURCE=1
  save_state
fi

sudo apt-get update
if ((WITH_SYSTEM_UPGRADE)); then
  log "Upgrading installed Ubuntu packages"
  sudo env DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
fi

log "Installing ROS 2, Gazebo integration, and MAVROS"
install_packages "ros-${ROS_DISTRO}-desktop" ros-dev-tools \
  "ros-${ROS_DISTRO}-ros-gz" "ros-${ROS_DISTRO}-mavros" \
  libgz-sim8-dev rapidjson-dev libopencv-dev libgstreamer1.0-dev \
  libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-bad \
  gstreamer1.0-libav gstreamer1.0-gl

set +u
# shellcheck disable=SC1090
source "/opt/ros/$ROS_DISTRO/setup.bash"
=======
  [[ -n "$ROS_APT_SOURCE_VERSION" ]] || fail "Could not find the ROS apt source release."
  ROS_APT_DEB="/tmp/ros2-apt-source.deb"
  curl -fL -o "$ROS_APT_DEB" \
    "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.${UBUNTU_CODENAME:-${VERSION_CODENAME}}_all.deb"
  sudo dpkg -i "$ROS_APT_DEB"
  rm -f "$ROS_APT_DEB"
fi

sudo apt update
sudo apt install -y ros-jazzy-desktop ros-dev-tools ros-jazzy-ros-gz \
  ros-jazzy-mavros libgz-sim8-dev rapidjson-dev libopencv-dev \
  libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
  gstreamer1.0-plugins-bad gstreamer1.0-libav gstreamer1.0-gl

set +u
# shellcheck disable=SC1091
source /opt/ros/jazzy/setup.bash
>>>>>>> Stashed changes
set -u

log "Configuring rosdep"
if [[ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]]; then
  sudo rosdep init
<<<<<<< Updated upstream
  CREATED_DEFAULT_ROSDEP_SOURCE=1
fi
if [[ ! -f /etc/ros/rosdep/sources.list.d/00-gazebo.list ]]; then
  curl -fsSL https://raw.githubusercontent.com/osrf/osrf-rosdep/master/gz/00-gazebo.list |
    sudo tee /etc/ros/rosdep/sources.list.d/00-gazebo.list >/dev/null
  CREATED_GAZEBO_ROSDEP_SOURCE=1
fi
save_state
rosdep update
rosdep resolve "gz-${GZ_VERSION}" >/dev/null

log "Preparing ArduPilot at $ARDUPILOT_DIR"
if [[ ! -e "$ARDUPILOT_DIR" ]]; then
  mkdir -p "$(dirname "$ARDUPILOT_DIR")"
  git clone --recurse-submodules https://github.com/ArduPilot/ardupilot.git "$ARDUPILOT_DIR"
  CREATED_ARDUPILOT=1
  save_state
elif [[ ! -d "$ARDUPILOT_DIR/.git" ]]; then
  die "$ARDUPILOT_DIR exists but is not a Git checkout. Move it or choose another ARDUPILOT_DIR."
fi

case "$(git -C "$ARDUPILOT_DIR" remote get-url origin)" in
  *github.com:ArduPilot/ardupilot.git|*github.com/ArduPilot/ardupilot.git|*github.com/ArduPilot/ardupilot) ;;
  *) die "$ARDUPILOT_DIR is not an ArduPilot/ardupilot checkout; refusing to modify it." ;;
esac
git -C "$ARDUPILOT_DIR" fetch --tags origin
ARDUPILOT_TARGET="$(git -C "$ARDUPILOT_DIR" rev-parse "${ARDUPILOT_REF}^{commit}" 2>/dev/null)" || \
  die "ArduPilot ref $ARDUPILOT_REF does not exist."
if [[ "$(git -C "$ARDUPILOT_DIR" rev-parse HEAD)" != "$ARDUPILOT_TARGET" ]]; then
  [[ -z "$(git -C "$ARDUPILOT_DIR" status --porcelain)" ]] || \
    die "$ARDUPILOT_DIR has local changes. Clean or save them before switching to $ARDUPILOT_REF."
  git -C "$ARDUPILOT_DIR" checkout --detach "$ARDUPILOT_TARGET"
fi
git -C "$ARDUPILOT_DIR" submodule update --init --recursive

# The upstream helper installs the correct ArduPilot Python/apt prerequisites,
# but it also writes shell files under HOME. Give it an installer-owned HOME so
# those changes and its virtual environment can be removed cleanly.
ARDUPILOT_UPSTREAM_HOME="$STATE_DIR/ardupilot-home"
mkdir -p "$ARDUPILOT_UPSTREAM_HOME"
TMP_APT_SNAPSHOT="$(mktemp /tmp/lrs-urk-apt-before-ardupilot.XXXXXX)"
dpkg-query -W -f='${binary:Package} ${db:Status-Abbrev}\n' 2>/dev/null |
  awk '$2 == "ii" { print $1 }' | sort -u > "$TMP_APT_SNAPSHOT"
for package in modemmanager brltty; do
  if package_installed "$package" && ! array_contains "$package" "${REMOVED_PACKAGES[@]}"; then
    REMOVED_PACKAGES+=("$package")
  fi
done
if ! id -nG "$USER" | tr ' ' '\n' | grep -Fxq dialout; then
  ADDED_DIALOUT=1
fi
save_state

env HOME="$ARDUPILOT_UPSTREAM_HOME" \
  DO_AP_STM_ENV=0 DO_PYTHON_VENV_ENV=0 \
  SKIP_AP_COV_ENV=1 SKIP_AP_COMPLETION_ENV=1 SKIP_AP_GIT_CHECK=1 \
  "$ARDUPILOT_DIR/Tools/environment_install/install-prereqs-ubuntu.sh" -y

record_new_apt_packages
rm -f -- "$TMP_APT_SNAPSHOT"
TMP_APT_SNAPSHOT=''

for candidate in "$ARDUPILOT_DIR/venv-ardupilot" "$ARDUPILOT_DIR/venv" \
    "$ARDUPILOT_DIR/.venv" "$ARDUPILOT_UPSTREAM_HOME/venv-ardupilot"; do
  if [[ -f "$candidate/bin/activate" ]]; then
    ARDUPILOT_VENV_DIR="$candidate"
    break
  fi
done
[[ -n "$ARDUPILOT_VENV_DIR" ]] || die "ArduPilot's Python virtual environment was not created."
save_state
set +u
# shellcheck disable=SC1090
source "$ARDUPILOT_VENV_DIR/bin/activate"
set -u

log "Building ArduPilot SITL Copter"
(
  cd "$ARDUPILOT_DIR"
  ./waf configure --board sitl
  ./waf copter
)

log "Preparing ArduPilot Gazebo at $ARDUPILOT_GAZEBO_DIR"
if [[ ! -e "$ARDUPILOT_GAZEBO_DIR" ]]; then
  mkdir -p "$(dirname "$ARDUPILOT_GAZEBO_DIR")"
  git clone --branch "$ARDUPILOT_GAZEBO_REF" --single-branch \
    https://github.com/ArduPilot/ardupilot_gazebo.git "$ARDUPILOT_GAZEBO_DIR"
  CREATED_ARDUPILOT_GAZEBO=1
  save_state
elif [[ ! -d "$ARDUPILOT_GAZEBO_DIR/.git" ]]; then
  die "$ARDUPILOT_GAZEBO_DIR exists but is not a Git checkout. Move it or choose another path."
fi

case "$(git -C "$ARDUPILOT_GAZEBO_DIR" remote get-url origin)" in
  *github.com:ArduPilot/ardupilot_gazebo.git|*github.com/ArduPilot/ardupilot_gazebo) ;;
  *) die "$ARDUPILOT_GAZEBO_DIR is not an ArduPilot/ardupilot_gazebo checkout; refusing to modify it." ;;
esac
git -C "$ARDUPILOT_GAZEBO_DIR" fetch origin "$ARDUPILOT_GAZEBO_REF"
GAZEBO_TARGET="$(git -C "$ARDUPILOT_GAZEBO_DIR" rev-parse "origin/${ARDUPILOT_GAZEBO_REF}^{commit}")"
if [[ "$(git -C "$ARDUPILOT_GAZEBO_DIR" rev-parse HEAD)" != "$GAZEBO_TARGET" ]]; then
  [[ -z "$(git -C "$ARDUPILOT_GAZEBO_DIR" status --porcelain)" ]] || \
    die "$ARDUPILOT_GAZEBO_DIR has local changes. Clean or save them before updating."
fi
if git -C "$ARDUPILOT_GAZEBO_DIR" show-ref --verify --quiet "refs/heads/$ARDUPILOT_GAZEBO_REF"; then
  git -C "$ARDUPILOT_GAZEBO_DIR" checkout "$ARDUPILOT_GAZEBO_REF"
else
  git -C "$ARDUPILOT_GAZEBO_DIR" checkout --track -b "$ARDUPILOT_GAZEBO_REF" "origin/$ARDUPILOT_GAZEBO_REF"
fi
git -C "$ARDUPILOT_GAZEBO_DIR" merge --ff-only "origin/$ARDUPILOT_GAZEBO_REF"

rosdep install --from-paths "$ARDUPILOT_GAZEBO_DIR" --ignore-src -r -y --rosdistro "$ROS_DISTRO"

if [[ ! -e "$ARDUPILOT_GAZEBO_BUILD_DIR" ]]; then
  CREATED_GAZEBO_BUILD=1
  save_state
fi
log "Building the ArduPilot Gazebo plugin in $ARDUPILOT_GAZEBO_BUILD_DIR"
GZ_VERSION="$GZ_VERSION" cmake -S "$ARDUPILOT_GAZEBO_DIR" \
  -B "$ARDUPILOT_GAZEBO_BUILD_DIR" -DCMAKE_BUILD_TYPE=RelWithDebInfo
GZ_VERSION="$GZ_VERSION" cmake --build "$ARDUPILOT_GAZEBO_BUILD_DIR" --parallel "$(nproc)"

log "Installing MAVROS GeographicLib datasets"
sudo env ROS_DISTRO="$ROS_DISTRO" bash -c \
  'source "/opt/ros/$ROS_DISTRO/setup.bash" && ros2 run mavros install_geographiclib_datasets.sh'

log "Downloading this project's Git LFS objects"
git lfs install
git -C "$PROJECT_ROOT" lfs pull

remove_environment_block() {
  local output starts ends
  [[ -f "$BASHRC_FILE" ]] || return 0
  starts="$(grep -Fxc "$ENV_START" "$BASHRC_FILE" || true)"
  ends="$(grep -Fxc "$ENV_END" "$BASHRC_FILE" || true)"
  [[ "$starts" == "$ends" ]] || \
    die "The managed markers in $BASHRC_FILE are incomplete; refusing to rewrite it."
  output="$(mktemp "${BASHRC_FILE}.lrs-urk.XXXXXX")"
  awk -v start="$ENV_START" -v end="$ENV_END" '
    $0 == start { skipping = 1; next }
    $0 == end   { skipping = 0; next }
    !skipping   { print }
  ' "$BASHRC_FILE" > "$output"
  chmod --reference="$BASHRC_FILE" "$output"
  mv -f -- "$output" "$BASHRC_FILE"
}

log "Writing the managed environment block to $BASHRC_FILE"
touch "$BASHRC_FILE"
remove_environment_block
{
  printf '\n%s\n' "$ENV_START"
  printf '# Generated by %q. Edit installer variables, not this block.\n' "$0"
  printf 'export ROS_DISTRO=%q\n' "$ROS_DISTRO"
  printf '[ -f %q ] && source %q\n' "/opt/ros/$ROS_DISTRO/setup.bash" "/opt/ros/$ROS_DISTRO/setup.bash"
  printf 'export GZ_VERSION=%q\n' "$GZ_VERSION"
  printf 'export ARDUPILOT_DIR=%q\n' "$ARDUPILOT_DIR"
  printf 'export ARDUPILOT_GAZEBO_DIR=%q\n' "$ARDUPILOT_GAZEBO_DIR"
  printf 'export ARDUPILOT_GAZEBO_BUILD_DIR=%q\n' "$ARDUPILOT_GAZEBO_BUILD_DIR"
  printf 'export LRS_URK_DIR=%q\n' "$PROJECT_ROOT"
  printf '[ -f %q ] && source %q\n' "$ARDUPILOT_VENV_DIR/bin/activate" "$ARDUPILOT_VENV_DIR/bin/activate"
  printf 'export PATH=%q${PATH:+:${PATH}}\n' "$ARDUPILOT_DIR/Tools/autotest"
  printf 'export GZ_SIM_SYSTEM_PLUGIN_PATH=%q${GZ_SIM_SYSTEM_PLUGIN_PATH:+:${GZ_SIM_SYSTEM_PLUGIN_PATH}}\n' "$ARDUPILOT_GAZEBO_BUILD_DIR"
  printf 'export GZ_SIM_RESOURCE_PATH=%q${GZ_SIM_RESOURCE_PATH:+:${GZ_SIM_RESOURCE_PATH}}\n' "$ARDUPILOT_GAZEBO_DIR/models:$ARDUPILOT_GAZEBO_DIR/worlds:$PROJECT_ROOT/models"
  printf '%s\n' "$ENV_END"
} >> "$BASHRC_FILE"
save_state

log "Installation complete"
printf 'Open a new terminal or run:\n  source %q\n\n' "$BASHRC_FILE"
printf 'Installed paths:\n  ArduPilot:        %s\n  ArduPilot Gazebo: %s\n  Plugin build:     %s\n' \
  "$ARDUPILOT_DIR" "$ARDUPILOT_GAZEBO_DIR" "$ARDUPILOT_GAZEBO_BUILD_DIR"
printf '\nA reboot is recommended before starting the three simulation processes.\n'
=======
fi
if [[ ! -f /etc/ros/rosdep/sources.list.d/00-gazebo.list ]]; then
  sudo wget -q \
    https://raw.githubusercontent.com/osrf/osrf-rosdep/master/gz/00-gazebo.list \
    -O /etc/ros/rosdep/sources.list.d/00-gazebo.list
fi
rosdep update

log "Installing ArduPilot in $ARDUPILOT_DIR"
if [[ ! -d "$ARDUPILOT_DIR/.git" ]]; then
  [[ ! -e "$ARDUPILOT_DIR" ]] || fail "$ARDUPILOT_DIR exists and is not a Git repository."
  git clone --recurse-submodules https://github.com/ArduPilot/ardupilot.git "$ARDUPILOT_DIR"
fi
cd "$ARDUPILOT_DIR"
git checkout Copter-4.7.0
git submodule update --init --recursive
Tools/environment_install/install-prereqs-ubuntu.sh -y

# Ubuntu 24.04's ArduPilot helper creates this virtual environment.
if [[ -f "$HOME/venv-ardupilot/bin/activate" ]]; then
  set +u
  # shellcheck disable=SC1091
  source "$HOME/venv-ardupilot/bin/activate"
  set -u
fi

./waf configure --board sitl
./waf copter

log "Installing ArduPilot Gazebo in $ARDUPILOT_GAZEBO_DIR"
if [[ ! -d "$ARDUPILOT_GAZEBO_DIR/.git" ]]; then
  [[ ! -e "$ARDUPILOT_GAZEBO_DIR" ]] || fail "$ARDUPILOT_GAZEBO_DIR exists and is not a Git repository."
  git clone https://github.com/ArduPilot/ardupilot_gazebo.git "$ARDUPILOT_GAZEBO_DIR"
fi
cd "$ARDUPILOT_GAZEBO_DIR"
git checkout ros2
rosdep install --from-paths . --ignore-src -r -y --rosdistro jazzy
GZ_VERSION=harmonic cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
GZ_VERSION=harmonic cmake --build build --parallel "$(nproc)"

log "Installing MAVROS datasets and downloading LRS-URK Git LFS files"
sudo bash -c \
  'source /opt/ros/jazzy/setup.bash && ros2 run mavros install_geographiclib_datasets.sh'
git lfs install
git -C "$LRS_URK_DIR" lfs pull

log "Adding paths to $BASHRC"
touch "$BASHRC"
TMP_BASHRC="$(mktemp)"
awk -v start="$ENV_START" -v end="$ENV_END" '
  $0 == start { skip = 1; next }
  $0 == end   { skip = 0; next }
  !skip       { print }
' "$BASHRC" > "$TMP_BASHRC"
cat "$TMP_BASHRC" > "$BASHRC"
rm -f "$TMP_BASHRC"

cat >> "$BASHRC" <<EOF

$ENV_START
source /opt/ros/jazzy/setup.bash
export ARDUPILOT_DIR="$ARDUPILOT_DIR"
export ARDUPILOT_GAZEBO_DIR="$ARDUPILOT_GAZEBO_DIR"
export LRS_URK_DIR="$LRS_URK_DIR"
export GZ_VERSION=harmonic
export PATH="\$ARDUPILOT_DIR/Tools/autotest:\$PATH"
export GZ_SIM_SYSTEM_PLUGIN_PATH="\$ARDUPILOT_GAZEBO_DIR/build:\${GZ_SIM_SYSTEM_PLUGIN_PATH:-}"
export GZ_SIM_RESOURCE_PATH="\$ARDUPILOT_GAZEBO_DIR/models:\$ARDUPILOT_GAZEBO_DIR/worlds:\$LRS_URK_DIR/models:\${GZ_SIM_RESOURCE_PATH:-}"
$ENV_END
EOF

log "Installation finished"
printf 'ArduPilot:        %s\n' "$ARDUPILOT_DIR"
printf 'ArduPilot Gazebo: %s\n' "$ARDUPILOT_GAZEBO_DIR"
printf 'Run: source %s\n' "$BASHRC"
printf 'A reboot is recommended.\n'
>>>>>>> Stashed changes
